### ISSUE TITLE
Create Resource Type form

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#100]
Create a form for adding and editing a ResourceType object. The form should live in `systers_portal/blog/forms.py`. Follow the example from the `TagForm` - it should inherit from the custom class `ModelFormWithHelper`, specify the model, the fields. Specify the same helper_class and helper_cancel_href, the later should point to the list of all resources.

Add a test for the form - `systers_portal/blog/tests/test_forms.py`. Don't forget to run all the tests, test coverage and flake8.

**Comment by Akanksha18** [comment]
i want to work on this

**Comment by jayesh92** [comment]
@ana-balica Do we also want a corresponding view ? As per the description you've only specified form.

**Comment by jayesh92** [comment]
@ana-balica If new view and template needs to be added, then I guess the view should be similar to `AddTagView` class ? Also what should be the url on which it should be initiated.
add tag url is binded to `r'^(?P<slug>\w+)/tag/add/$'`
