### ISSUE TITLE
Add tags snippet

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#101]
Create an HTML snippet for displaying common actions for manipulating tags. As an example, see "Community Actions", "News Actions" snippets. Call the snippet `tags_sidebar.html` inside `systers_portal/templates/blog/snippets`.

The snippet should contain 1 action (for the time being) - "Add tag". In HTML you should check if the user is authenticated and active. The snippet should be displayed only when the user has permission to add tags - `blog.add_tag`. Pay attention that this is not a row-level permission, but rather a typical Django permission.

Include the snippet to appear on news/resources list page and single news/resource page right above the membership button. 

Validate your HTML code using w3 validator. Use 2 spaces for HTML.

**Comment by BeingAnuj** [comment]
i want to work on this

**Comment by reachtarunhere** [comment]
I have a doubt why do we need Add Tag in list view? As per my understanding as tags are associated with News/Resource so their permissons must be locked to those models. 

Am I doing something wrong?  Would be glad if someone can point me in the right direction
