### ISSUE TITLE
SSL certificate for our production site

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#114]
Currently both Portal on http://portal.systers.org and Systers wiki on http://systers.org/systers-dev/doku.php use unencrypted connection even though we send sensitive data over the network (passwords during logins). We need to purchase an SSL certificate and install it on our server (I can do the later part). This way all our traffic will run over https and will be encrypted. 

@rosariorobinson Please take a loot at the following issue and if possible redirect to admins.

**Comment by rosariorobinson** [comment]
Thanks Ana. I'll get our IT team to get this done.


Rose

**Comment by tachyonlabs** [comment]
You can now get free SSL certificates through https://letsencrypt.org/ though it's still in beta.

**Comment by ana-balica** [comment]
@tachyonlabs thanks for recommendation :)

We have a secure connection https://portal.systers.org/ along with an insecure one http://portal.systers.org/

Would be nice to make http version to redirect to https. I will raise a separate issue on that.

Thanks @rosariorobinson!
