### ISSUE TITLE
Add new contributor guide for working on Portal Documentation 

### ISSUE THREAD

**Issue by willingc** [systers/portal#118]
New contributor documentation is extremely important for onboarding new developers and contributors to a project. Configuring development environments for an actively developed project can be challenging for new contributors. New contributors are learning the code base while dealing with operating system, virtual machine (vm and Docker), as well as language and dependencies (and their versions).

To provide an on-ramp for new developers, a contribution guide for working on Portal Documentation will be developed.

I am assigning this issue to @veniemi1. cc/ @rosariorobinson 

Development plan to follow in a separate comment.

**Comment by willingc** [comment]
@veniemi1 Okay, here's the current work plan. I want to get you contributing while we get your development environment set up in parallel. Since I'm primarily a Linux/Unix and OSX user, I'm a little rusty on Windows 7. No fear; I have access to a Windows 7 system if needed. Here's the plan:


- [ ]  Set up a free pythonanywhere.com account. This will give you access to a fully functional python development system in the cloud. You can get you started on using git, github, restructuredText, and Sphinx for documentation (we'll get to using these soon).
- [ ] pythonanywhere - 60 seconds to command line. Here is the user interface. To get a terminal (console), you will click on `Bash`:
![screen shot 2015-06-10 at 4 34 22 pm](https://cloud.githubusercontent.com/assets/2680980/8096719/e001ed4c-0f8e-11e5-9be7-2f82e5eb7cce.png)
- [ ] command line practice - Now that you have a Bash shell (also known as terminal or console). You should practice some commands and get comfortable with the command line. Some helpful commands: `cd`, `.`, `..`, `ls`, `pwd`, `mkdir`, `~`. Here's an example of my getting started with the Bash shell:
![screen shot 2015-06-10 at 4 20 27 pm](https://cloud.githubusercontent.com/assets/2680980/8096768/7a4f48a4-0f8f-11e5-99d0-82626f2f6032.png)
- [ ] working with git and github. The above image shows me creating a new directory, changing into the directory, and doing a `git clone` of the Syster's portal repository. Try it :)

Phew that's enough for the moment. As you get these done, please click in the checkbox of the item. This lets me know that you are done with each step. It also gives me a visual cue to ask if something is blocking you (while my expectation is that you will ask me questions, that skill doesn't come easily for some so this let's me proactively know if someone is having trouble).

[Note: we will not be using pythonanywhere for the Django development. just for docs and building skills. Although we could run Django on pythonanywhere, Postgres requires a paid account to do so.]
cc/ @rosariorobinson

**Comment by veniemi1** [comment]
I was able to set up my pythonanywhere account pretty easily and have played with some of the command line commands a bit. However, I will do more tomorrow morning like I wrote in my email.

**Comment by willingc** [comment]
@veniemi1 Excellent!

**Comment by ana-balica** [comment]
@willingc thanks for helping out and guiding @veniemi1
Since we don't have any beginners cli/python/django/deployment docs, I am thinking that we could move all steps above to portal documentation. I am usually redirecting new contributors to DjangoGirls tutorial, but we can definitely create our own guide. What do you think?

**Comment by willingc** [comment]
@ana-balica No problem :)

Down the line, it would be good to move all contributor docs within the project. For now, the DjangoGirls tutorial installation instructions are highly tested and probably the best, most used installation instructions for Django and Python3 at the moment. I think we rely heavily on their content for now with references from our docs to theirs or include their docs with attribution (which is likely possible but wouldn't get all the bug fixes that they find from users at their events). Given the resources that we have for the portal project currently, I think our time will be best spent referring to their docs and clarifying as needed in our docs. I think updating the installation docs more completely would be a good GSOC contributions during the application period next year. Does that sound good to you?

**Comment by ana-balica** [comment]
Yes! And I agree it's more practical to refer to DjangoGirls, rather than having our own.

Next year contribution sounds rather far away. Moreover most GSoC students are averagely experienced and rarely loop through the whole beginners cycle. Would it possible for @veniemi1 to help up out with beginners docs once she is finished? Her perspective is valuable.

I have one small concern though - once a new contributor is finished with installation guide, it will become a little bit of a problem to offer them small beginners tasks. I am currently trying to come up with some.

**Comment by willingc** [comment]
@ana-balica Next year always seems so far away and then it sneaks up on us ;)

Configuration is a pain which is essentially what the installation instructions guide the developer through. While true that many come to GSoC with experience in software development of a language, my experience with teaching post-docs and down is that the experience with development tools is not as strong. Compound the lack of tools experience with the many dependencies and permutations of environments and the result is a big headache. 

I also view GSoC as a multiyear experience. Students that perhaps are not selected the initial application year will likely build understanding and skills over the years and participate in later years. Also, a positive beginner onboarding experience is a valuable way to keep and attract newcomers to computer science as well as retain them in the field.

Your concern on having enough bite-size beginner task is very reasonable. It's hard to come up with the ideas. Before GSoC and outreach events or sprints, I typically go through my projects and scramble to label suitable issues. I'm glad that you are proactively thinking of some :+1:
