### ISSUE TITLE
Update all documentation from fig (deprecated) to Docker compose 

### ISSUE THREAD

**Issue by willingc** [systers/portal#119]
fig is now deprecated. Docker compose (http://docs.docker.com/compose/install/) is the replacement. README.md should be updated as well as any general documentation referring to fig.

**Comment by ana-balica** [comment]
Initially I planned to have a Docker container for Rose to test the app, but eventually I found out the setup and installation are too tedious for "trying out" a product. Hence I was thinking removing the `Dockerfile`. Besides having a Docker container in production, are there any benefits of keeping a Docker?

**Comment by willingc** [comment]
It's likely worth keeping. Docker is still a mild nuisance if working from a non-Linux machine since you then have to deal with the boot2docker vm and its configuration for servers. For now, I would just leave it ;)

**Comment by ana-balica** [comment]
Solved in a084843
