### ISSUE TITLE
Review documentation for installation of development environment on Windows 7

### ISSUE THREAD

**Issue by willingc** [systers/portal#120]
I'm assigning this task to @veniemi1 and she will be pairing with me.

First steps for Windows 7 to check:
- [x] Installing Python: Follow directions in DjangoGirls documentation section 3 http://tutorial.djangogirls.org/en/python_installation/index.html (make sure you do the step that adds python to the PATH)
- [x] Verify Python installation: From the command line (see DjangoGirls section 2 if needed), enter `python --version` and Windows 7 should return the correct python version. If not my recommendation would be to uninstall python, reboot, and reinstall python.
- [x] Make a note of your PATH settings.

**Comment by ana-balica** [comment]
I believe this was done. If any issues with Windows persist, one can reopen and add specific tips in our README or [here](http://systers-portal.readthedocs.org/en/develop/).
