### ISSUE TITLE
Remove use of 'django-countries'

### ISSUE THREAD

**Issue by exploreshaifali** [systers/portal#123]
Portal used 'django-countries' package to validate countries data in 'users' app. In 'meetup' app it is using 'django-cities-light' package to validate countries, region and cities data. So we can safely exclude 'django_countries' and make use of 'django-cities-light' in 'users' app also.

**Comment by payal97** [comment]
I want to work on this issue.

**Comment by shriyanka** [comment]
@exploreshaifali  
Hi.. If no one is currently working on it can I take up this task ??

Thanks,
Kajal

**Comment by tapasweni-pathak** [comment]
Closed with [0194d1e](https://github.com/systers/portal/commit/0194d1ef2af445746486e366e6a95b31559e8553).
