### ISSUE TITLE
Venue should be CharField.

### ISSUE THREAD

**Issue by exploreshaifali** [systers/portal#142]
Meetup venue is TextField, it should be CharField instead.

**Comment by varunnaganathan** [comment]
i want to work on this.I have submitted a Pull Request.Kindly review

**Comment by varunnaganathan** [comment]
Please Review Pull Request
https://github.com/systers/portal/pull/149

**Comment by varunnaganathan** [comment]
Do provide details on the "continuous-integration/travis-ci/pr" check that fails.The check fails irrespective of the change.I figure it is some Key Error local to my machine and probably not related to the bug.

**Comment by varunnaganathan** [comment]
PR review??

**Comment by kunalsharma05** [comment]
I would like to work on this Issue.

**Comment by shriyanka** [comment]
@rosariorobinson Please review the PR.

Thanks :)
