### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#146]
Speed up test with mocks and mommy. The general rule is to avoid writing to the database.

**Comment by nikhilweee** [comment]
Hi, @ana-balica 
I'm willing to work on this.

**Comment by nikhilweee** [comment]
@ana-balica: I'm facing some issues while working on this, can you help me out?
* I cannot find a way to avoid writing to the database while testing forms. For every test case, the `form.save()` method needs to be called, which requires database transaction.
* `Mock` objects cannot be used while testing string representation as `str(Mock)` doesn't return the desired value
* Testing views are ruled out as their response directly relies on database queries.

This leaves very less scope of speeding up tests. I'll be glad if you help me out with this.
