### ISSUE TITLE
Create Page for Mobile Apps

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#148]

**Comment by akankshaakanksha** [comment]
Hello, 
Is this an open issue? I am a new contributor to Systers and would love to begin contributing. Can you give me a description of what needs to be done.

**Comment by prachiagrawal269** [comment]
@rosariorobinson  @jproft Can anyone of you provide a bit detailed description as of what exactly is the page about and should be the content of the required page?

**Comment by jproft** [comment]
At the moment nothing else needs to be done with this. Thanks @akankshaakanksha and @prachiagrawal269.
