### ISSUE TITLE
Travis CI Build failures because of SECRET_KEY

### ISSUE THREAD

**Issue by sudheesh001** [systers/portal#153]
One of the setup steps involves the export of the secret key `export SECRET_KEY=foobarbaz`
but this doesn't happen on Travis CI causing the build failures. This can be easily fixed by adding `SECRET_KEY` exports to the yml file.

**Comment by daminisatya** [comment]
@sudheesh001  I read the document on the Travis build. Check this out. 
![capture](https://cloud.githubusercontent.com/assets/6227784/13487697/e544fe54-e141-11e5-90ee-55bda3b4658d.PNG)
