### ISSUE TITLE
Query regarding installation instructions

### ISSUE THREAD

**Issue by smarshy** [systers/portal#156]
I ran into errors regarding the second and third instructions while proceeding with the portal installation stepwise on Ubuntu 14.04.

Step 2 links to Django girls repository which shows how to install psycopg using pip.  However, on trying to install psycopg without python3-dev first, I ran into the following error

`fatal error: Python.h: No such file or directory #include <Python.h>`

The next error I ran into was missing libpq header configuration files. As mentioned [here](http://initd.org/psycopg/docs/install.html), these seem to be the prerequisites to installing psycopg. Perhaps the order of instructions 2 and 3 should be switched.

Also, on running instruction 3 `sudo pip install python3-dev`, the following error pops up

```
Could not find any downloads that satisfy the requirement python3-dev
Cleaning up...
No distributions at all found for python3-dev
```

I ran `pip search python3-dev` to see if the package existed but could not find an exact match.
Maybe apt-get should be used instead?

I am proposing a fix to the instructions but since no one else seems to have run into this error, it would be nice to get a confirmation on this. It might be because I didn't have any packages pre-installed. Please check in a similar situation. Also, please check if these are just OS specific.

**Comment by kunalsharma05** [comment]
Hey, `sudo apt-get install` does in fact work. First, you need to setup python3 on your system (development version should work) and then you can easily install the required libraries in your virtual environment site-packages using pip.If you need anything else I would be happy to help.
Hope this helps and clears your doubts. :)

**Comment by smarshy** [comment]
@kunalsharma05 Thanks for confirming :)

**Comment by prachiagrawal269** [comment]
@smarshy Even i got the same error while installation. Indeed  "sudo pip install python3.4-dev" worked for me (as i have python3.4 installed in my system). Also there is a slight difference between installation commands when working behind proxy. Like one should use "-E" flag along with "sudo" to export all the environmental variables. I got this solution after a lot of search on line. May be these kind of specifications also included in the documentation.

**Comment by payal97** [comment]
@prachiagrawal269 Even I had trouble during installation due to proxy. Sent in a patch for the same. :)

**Comment by smarshy** [comment]
@prachiagrawal269 hey, Were you able to use `sudo pip install python3.4-dev` successfully? Also, could you put in the command where you needed the flag. I mostly run into -E flag error when I am adding ppa repositories upstream and using sudo pip, but in this case I couldn't find the package in pypi itself

**Comment by prachiagrawal269** [comment]
@smarshy I made a mistake while mentioning the command .I checked my command history and found out that I command that I executed was "sudo apt-get install python3.4-venv" and not "sudo pip install python3.4-dev". Sorry for the mistake. 
I used the "-E" flag while installing the virtualenv using "sudo -E pip install virtualenv".
Thanks for pointing out.
