### ISSUE TITLE
Functionalities missing in meetup page

### ISSUE THREAD

**Issue by Gayathrimenakath** [systers/portal#158]
I find that the following functionalities missing in the meetups page for a particular location: 
1. Clicking on Join this Meetup button produce no results.
2. Clicking on various other links ( add member, remove member etc ) on the sidebar do not produce any changes, even for the Meetup admin .

I propose the following should happen, when clicking on the "Join this Meetup" button: 
1. A logged in user visits a Meetup page in a location and finds the 'Join this Meetup' button and clicks on it. 
2. The admin of the meetup should see his request listed in the 'See Join Requests' link on the right sidebar 
3. The admin of the event should have the right to accept/reject the request from that page. 
4. The new member profile should get listed in the 'Members' section along with other members. 

Currently, an admin has to go to the admin panel to accept/reject an application, while we still have a button available for public in the Meetups page, which seems ambiguous.

**Comment by ana-balica** [comment]
Hi!

Yes, this is one of the features that we want to implement. Most of the parts of the meetup app will not work at this point. This is something that you might want to include in your proposal, additionally with some technical implementation. Thanks.

**Comment by Gayathrimenakath** [comment]
@ana-balica Thank you
