### ISSUE TITLE
[Production] Always redirect from http to https

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#159]

**Comment by nikhilweee** [comment]
@ana-balica There's a SECURE_SSL_REDIRECT setting in Django 1.8 which makes the fix easy peasy. When is the portal upgrading to a newer Django?

**Comment by kunalsharma05** [comment]
@ana-balica @nikhilweee I think that too can be done in Django versions <1.8:

**1.** By changing the redirect rule in the web server's settings. For e.g. in nginx: 
```
server {
   listen 80;
   rewrite ^(.*) https://$host$1 permanent;
}
```
To make sure that full links also get redirected to https like in HttpResponseRedirect we can just add this to wsgi.py file: 
`os.environ['HTTPS'] = "on"`

Also to ensure that there is no leak of information if someone tries to retrieve the cookies one can simply add this in the settings.py file:
```
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

```
**2.** Another method of allowing the redirect would be by using the package **django-secure** which offers the `SECURE_SSL_REDIRECT` in settings.py, to use this we need to add 'djangosecure' to installed apps  in settings.py and add the middleware (on the top of the list):
```
MIDDLEWARE_CLASSES = (
    ‘djangosecure.middleware.SecurityMiddleware’,
    …
)
```
Note: Here's the documentation of django-secure [(http://django-secure.readthedocs.org/en/v0.1.2/settings.html#secure-ssl-redirect)] and cokies can be made secure as done above.

Although, I completely agree with the answer given by @nikhilweee as the Django 1.8 has assimilated the django-secure as a default and that the scope of the current project can look for migrating the portal to a newer django version.

@ana-balica if needed I can provide a PR with the above mentioned settings (without the web server configuration, ofcourse). :)

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak  what I need to do in this?

**Comment by tapasweni-pathak** [comment]
This [may](https://docs.djangoproject.com/en/1.11/topics/security/) help.

**Comment by tapasweni-pathak** [comment]
Important issue if this happens even after develop gets deployed.
