### ISSUE TITLE
Change btn-lg OAuth login buttons to use friendly icon buttons 

### ISSUE THREAD

**Issue by tonythomas01** [systers/portal#161]
The current buttons in the signup page : 
![selection_051](https://cloud.githubusercontent.com/assets/4214481/13561215/51d09cca-e450-11e5-86b7-2cf4d794e8ac.png)

looks ugly, and should be replaced with buttons like : 
![selection_052](https://cloud.githubusercontent.com/assets/4214481/13561222/6ff9d090-e450-11e5-85db-edba7c282193.png)

This would help avoid page scroll in Sign Up page for normal browsers and mobiles.

**Comment by Gayathrimenakath** [comment]
Sounds sensible, I will send a patch for this.

**Comment by Gayathrimenakath** [comment]
Please review this. https://github.com/systers/portal/pull/166

**Comment by tonythomas01** [comment]
@Gayathrimenakath : works. nice one! Can you attach a screenshot too here ?

**Comment by Gayathrimenakath** [comment]
![login](https://cloud.githubusercontent.com/assets/9162502/13567473/82887ffa-e481-11e5-94b0-732bda26e0b1.png)

**Comment by prachiagrawal269** [comment]
Hello,
I felt like adding colors to the social network buttons would be more intuitive, so i tried implementing the same by enhancing the PR #166 by @Gayathrimenakath . I just added colors to the buttons on both "contact" page and the "login" page (carrying forward the changes made by @Gayathrimenakath in the file systers_portal/templates/socialaccount/snippets/provider_list.html)

**Comment by kunalsharma05** [comment]
Hey,
@prachiagrawal269 I just saw that you also added the background colours, so I changed my design to be flat with the colours and a transition and hover.
@tonythomas01 Please review the pull request #174 that has the hover effect on both the sign up pages and the contact pages.
![screenshot from 2016-03-09 20 43 35](https://cloud.githubusercontent.com/assets/14278351/13639674/d23bb1cc-e637-11e5-875c-ac780c630105.png)
![screenshot from 2016-03-09 20 43 47](https://cloud.githubusercontent.com/assets/14278351/13639673/d22d65a4-e637-11e5-8338-b4ca27c12c1e.png)

**Comment by Himanshi-Khandelwal** [comment]
what all is left to work in this issue?
