### ISSUE TITLE
Remove unnecessary divider in navbar drop-down menu when not signed in  

### ISSUE THREAD

**Issue by tonythomas01** [systers/portal#162]
When not signed in: 
![image](https://cloud.githubusercontent.com/assets/4214481/13561428/0af56cce-e453-11e5-8a9b-f4a3324fcd0b.png)

has an extra 
<li role="presentation" class="divider"></li>
which should not be there, to make it look better as in: 

![selection_054](https://cloud.githubusercontent.com/assets/4214481/13561443/30ba5938-e453-11e5-8d22-a28896772a43.png)

Have't tested this after login though

**Comment by Gayathrimenakath** [comment]
I would like to send a patch for this.
