### ISSUE TITLE
Design issues with 'Edit my profile' page 

### ISSUE THREAD

**Issue by tonythomas01** [systers/portal#163]
The current design of 'Edit my profile page': 
1. Use only left portion of the screen, and loads of empty space 
2. Profile upload button do not have same style as other buttons on the page 
3. Design inconsistent with 'Change password', 'Sign Up' or 'Sign In' page 

To make things look good: 
1. 'Edit my profile' page should be centered, in a col-md-4 or something like that as in 'Change-Password' 
2. Change button style to match 'Sign Up' button.

**Comment by smarshy** [comment]
@tonythomas01 working on this :)

**Comment by payal97** [comment]
I would like to work on this

**Comment by payal97** [comment]
@smarshy just saw your comment. I guess i'll wait for the next issue then. :P

**Comment by smarshy** [comment]
@payal97 :+1:  Thanks for understanding :)

**Comment by payal97** [comment]
:smile:

**Comment by daminisatya** [comment]
#169

**Comment by smarshy** [comment]
@daminisatya Hi, I was planning to get to this by the end of the day. I see you have put in a PR. Looks good :+1:

**Comment by Dhara159** [comment]
Hi, I'm Dhara Vihol. I want to start contributing to Systers open source projects. I would like to work on this issue and start my contribution. Can i take this issue?

**Comment by tonythomas01** [comment]
> Hi, I'm Dhara Vihol. I want to start contributing to Systers open source projects. I would like to work on this issue and start my contribution. Can i take this issue?
 
I dont think you have to wait for someone to allow you to take this (unless this is listed as a special task for some program, etc). Just go on - submit a PR as per the contributing guidelines.

**Comment by tonythomas01** [comment]
@MeepyMay why are you closing these issues ? Are they fixed ?
