### ISSUE TITLE
gitignore lacks basic rules, bringing in migration data upstream

### ISSUE THREAD

**Issue by tonythomas01** [systers/portal#173]
The current .gitignore files lacks various rules of Django like: 
    *.log
*.pot
*.pyc
__ pycache__/
local_settings.py
migrations/

Standard templates are available in the internet, and should be added to the current `.gitgnore` file to make sure these issues never happen again like https://github.com/systers/portal/commit/eeb03a500c8315fcf16af9268887468782a0aa57

**Comment by Gayathrimenakath** [comment]
I would like to fix this

**Comment by Gayathrimenakath** [comment]
Please review this #175

**Comment by kunalsharma05** [comment]
@Gayathrimenakath @tonythomas01 I think we should've left out migrations since many bugs require models.py file getting changed and since it is usually seen on git that migrations are pushed with a fix, I think it can be ignored when needed rather than ignoring them for every push? Anyways the fix by @Gayathrimenakath covers most of the general ignores :)

**Comment by tonythomas01** [comment]
@kunalsharma05 its true that most of the changes require changes to models.py, but I am not sure why someone should push the migrations too. It can leave developers in avoidable conflicts, and could be always generate clean with `makemigrations` and `migrate`

We got support and distress over http://stackoverflow.com/questions/28035119/should-i-be-adding-the-django-migration-files-in-the-gitignore-file though.

**Comment by kunalsharma05** [comment]
@tonythomas01 I agree with you but the projects I worked on mostly had web hooks from GitHub the Server and vice versa. So then a user may create a initial migration,lets call it 0001. Similarly they thought of making another migration for the change and named it 0002, now if the migrations aren't pushed the other contributor may face problems as for him they will be in one migration file that they may have created after running a pull command.
I completely agree with you that this is **case specific** and may change from place to place where the work conditions are different.
So I was just thinking that different users should stay on the same page especially when the development and deployed are connected to each other. 
Anyways thanks for pointing it out, from now on I will avoid sending migrations for the development versions :)

**Comment by tonythomas01** [comment]
yeah. you should take a look at #164 too.
