### ISSUE TITLE
'edit profile' and other options in another user's profile veiw

### ISSUE THREAD

**Issue by payal97** [systers/portal#177]
On portal.systers.org, when I view another user's profile, I get the following options, which I should not be getting - 
![screenshot from 2016-03-14 00 01 55](https://cloud.githubusercontent.com/assets/14258784/13730602/6b9bdc28-e94b-11e5-82a4-2866ed8f65c9.png)

![screenshot from 2016-03-14 00 09 00](https://cloud.githubusercontent.com/assets/14258784/13730606/802a5908-e94b-11e5-8ac0-b47d078c67c9.png)

All those options redirect to my own profile page.

This does not happen in the development version though -
![screenshot from 2016-03-14 00 01 50](https://cloud.githubusercontent.com/assets/14258784/13730617/b9544d06-e94b-11e5-8ebc-9cd868d0fb5d.png)

**Comment by tapasweni-pathak** [comment]
*This is not reproducible with develop branch.*
