### ISSUE TITLE
Sign Up Button

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#181]
Does Sign Up take users through approval process?

**Comment by tapasweni-pathak** [comment]
Signup is not authenticating the email of the user.

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak  do we need to first authenticate before sign up? Or sign up button can be pressed but user won't be able to log in unless email confirmation is done

**Comment by tapasweni-pathak** [comment]
Signup should authenticate the email of the user, only then user should be allowed to login. If the user try to login without confirming their email they should get an error message that a confirmation has been sent to email id.

**Comment by sa7i** [comment]
@tapasweni-pathak  Would this be okay?
![image](https://user-images.githubusercontent.com/13400691/31764370-927b217c-b4de-11e7-866e-4a6ccc28def2.png)
![image](https://user-images.githubusercontent.com/13400691/31764385-9ba17f08-b4de-11e7-831f-124c666ece95.png)
![image](https://user-images.githubusercontent.com/13400691/31764390-9f620cca-b4de-11e7-9458-4712c699a4e8.png)
