### ISSUE TITLE
Correct README.md

### ISSUE THREAD

**Issue by yatna** [systers/portal#191]
The README says-

>  If you are on Linux, enter http://0.0.0.0:8000 in your browser.

However, the app gives an error at that URL 
![screenshot from 2017-03-01 17 23 47](https://cloud.githubusercontent.com/assets/8321130/23458870/f3c804fa-fea3-11e6-8503-226558b708de.png)

Instead, it runs on http://localhost:8000 in the browser
![screenshot from 2017-03-01 17 23 56](https://cloud.githubusercontent.com/assets/8321130/23458892/0d7139da-fea4-11e6-9bc0-f672163aa6c1.png)
@ana-balica I would like to fix this.

**Comment by tonythomas01** [comment]
>The README says- If you are on Linux, enter http://0.0.0.0:8000 in your browser. However, the app gives an error at that URL

That specific quote was for `docker-compose up` command, and not for `$ python manage.py runserver`. 

If you were trying this on `python manage.py runserver`, feel free to close this bug as `invalid`.
