### ISSUE TITLE
[Bug] 'Browse' option in 'Edit Profile' lets choose any file type

### ISSUE THREAD

**Issue by yatna** [systers/portal#192]
The 'Browse' option to upload profile picture, lets the user choose any file type. Only after pressing the upload button it gives the error message if the file type is incorrect. 
![screenshot from 2017-03-01 17 50 57](https://cloud.githubusercontent.com/assets/8321130/23459725/a7a9046c-fea7-11e6-8f43-e08291f1b467.png)
It would be better if we can make the browse button to display only image type files (like jpg, jpeg, png etc)
@ana-balica I would like to work on this.

**Comment by tonythomas01** [comment]
Feel free to submit a PR as per https://github.com/systers/portal/blob/develop/docs/develop/contributing.rst

**Comment by Himanshi-Khandelwal** [comment]
@yatna @tonythomas01 @tapasweni-pathak  When I tried this , it doesn't let me cgoose any file type. Error message is visible.
![screenshot from 2017-10-17 19 59 23](https://user-images.githubusercontent.com/17119462/31670706-d0f5be9a-b375-11e7-85d7-90ce996cdfd7.png)

**Comment by tapasweni-pathak** [comment]
Thanks for checking and confirming, not reproducible now, closing this.
