### ISSUE TITLE
Add details to 'Edit Profile' Form

### ISSUE THREAD

**Issue by yatna** [systers/portal#193]
1. Inputs Fields like 'Homepage' and 'Blog' require user to enter a URL. However, user comes to know this only when he/she has press the submit button once with some incorrect entry. It would be better if we could explicitly tell the user to enter a URL, by adding a message like - "Enter URL" or "eg http://myblog.com" to the label.
2. We should mention the max length in the label which the user can enter beside the 'First Name' and 'Last Name' fields.
@ana-balica  I would like to work on this.

**Comment by tonythomas01** [comment]
Feel free to add that to the corresponding `forms.py`, and submit a PR as per https://github.com/systers/portal/blob/develop/docs/develop/contributing.rst

**Comment by tapasweni-pathak** [comment]
@yatna How do you plan to show the user before submitting?

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak I have created a PR for the second todo. Please review it once.
Also, can you please explain whether adding "Enter Url" in `forms.py` is enough for the first todo?

**Comment by tonythomas01** [comment]
I dont think this open-later tag makes any sense at all. That is not a standard workflow.
