### ISSUE TITLE
Countries not available as drop downs 

### ISSUE THREAD

**Issue by mish24** [systers/portal#194]
While filling the edit profile form, country is not available as drop down.

**Comment by namanrjpt** [comment]
@mish24 If you are not working on this, I would like to take this up. I might need your help though :smile:

**Comment by mish24** [comment]
@namanrjpt Cool :) Do tell me if you need any help!

**Comment by namanrjpt** [comment]
@mish24 Nothing is broken here. After a lot of head scratching it just turned out that the databse is not populated. To do the same you just have to use:

> ./systers_portal/manage.py cities_light

from your repo's root

**Comment by mish24** [comment]
Ah alright! Thanks alot. @namanrjpt
