### ISSUE TITLE
Current section is not highlighted in the navigation bar

### ISSUE THREAD

**Issue by namanrjpt** [systers/portal#196]
Currently the top navigation bar does not highlight the active section/app of the portal. Though small, this could create a little confusion on addition of a more complex app with many pages (meetup feature?) in future, if not now. IMO fixing this can enhance the UX significantly.

![screenshot from 2017-03-08 00-16-28](https://cloud.githubusercontent.com/assets/16839029/23672374/843dc052-0394-11e7-807d-f8c89877ba4c.png)
Here the options in the top nav bar are of same style. :smile:

**Comment by pandilladivya** [comment]
@namanrjpt Are you Working on this issue ?

**Comment by namanrjpt** [comment]
@pandilladivya There are a few ways by which this can be fixed. I'm searching for the best one. So yes, im on it.

**Comment by namanrjpt** [comment]
Submitted [PR](https://github.com/systers/portal/pull/198). Kindly review it :smile: 
![Image](https://cloud.githubusercontent.com/assets/16839029/23843449/d533977e-07e1-11e7-9e02-8c700903133c.gif)

**Comment by tonythomas01** [comment]
<needs more work there. please dont use JS to get this done>

**Comment by sonakshisaxena1** [comment]
I think it's already been fixed. 
@tapasweni-pathak can you check it once?

**Comment by tapasweni-pathak** [comment]
Yep, thanks for checking!

**Comment by arunikayadav42** [comment]
I am interested to work on this issue,can somebody help me out?

**Comment by arunikayadav42** [comment]
on how to proceed?

**Comment by vigzmv** [comment]
Claiming this
