### ISSUE TITLE
Adding Social Network platform authentication feature

### ISSUE THREAD

**Issue by mish24** [systers/portal#199]
Not related to GSoC. I would like to work on this independently :)

**Comment by tonythomas01** [comment]
Did you mean OAuth ? Like, using https://github.com/pennersr/django-allauth maybe ?

**Comment by mish24** [comment]
@tonythomas01 Yup. I wanted to use `django-allauth` only. It can benefit the portal in many ways.

**Comment by tonythomas01** [comment]
> @tonythomas01 Yup. I wanted to use django-allauth only. It can benefit the portal in many ways.
Right. I think the prduction version already have something like that - check http://portal.systers.org/accounts/login/  && https://github.com/systers/portal/blob/develop/requirements/prod.txt#L3

Even though, I would love to see better buttons, with everything on the same row (with social network icon there).

**Comment by mish24** [comment]
@tonythomas01 Aaah, I guess I missed it somehow. I can add social platform buttons, and then there's the issue of being able to access other user's details through urls. I will focus on them. Thanks for helping with this! :)

**Comment by tonythomas01** [comment]
Great to know. You can just use  <i class="fa fa-{{ provider.id }}"></i> to take in the icon automatically from font-awesome.

**Comment by tonythomas01** [comment]
by the way, that bug was tracked in https://github.com/systers/portal/issues/161

I think no one merged it :-(
