### ISSUE TITLE
Migrate to Django version 1.11 and Python 3.6

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#201]
With latest version of OS, >Ubuntu 16.04, Debian 9 Stretch having Python >= 3.5, Django 1.7.7 is having issues.

```
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
```
because HTMLParseError is deprecated from Python 3.3 onwards and removed with Python 3.5. Temporary fix of this [not a good option] is to downgrade Python version or a better way is to upgrade Django version to >1.7. Also with Django 1.8 in guardian/admin.py change ```module_name``` to ```model_name``` at all its occurrences.

Migrate portal to newer Django version, 1.11.

**W/ this also move all used packages in Portal to latest and compatible one.** https://github.com/systers/portal/issues/290

**Comment by bhavya-reddy** [comment]
working on this issue

**Comment by arunikayadav42** [comment]
I am keen on working on this issue,can somebody help me out?

**Comment by sa7i** [comment]
This is a huge task to work on. I've already worked on this and opened a [PR](https://github.com/systers/portal/pull/257) for it, ready to be merged.
