### ISSUE TITLE
Fix spelling mistake in Documentation

### ISSUE THREAD

**Issue by mansimarkaur** [systers/portal#202]
There is a spelling mistake in PEP8 section of the Pre-requisites documentation.
Here's the link to it: http://systers-portal.readthedocs.io/en/develop/develop/prerequisites.html#pep8

**Comment by namratab94** [comment]
Is anyone working on this?

**Comment by mansimarkaur** [comment]
@namratab94 nobody is working on this yet. If you want to work on it, @tapasweni-pathak can assign the issue to you.

**Comment by namratab94** [comment]
I would like to work on it. @tapasweni-pathak can you please assign this issue to me?

**Comment by tapasweni-pathak** [comment]
@namratab94 Issue can be assigned only within the people of organization or project. Please go ahead and send a fix, would be happy to merge. I tagged this for first-timers-only though.

**Comment by namratab94** [comment]
This would be my first contribution to Systers. If I'm not wrong, I've not made any contribution to any of the Systers' projects till date. Working my way around the contribution guide and then hopefully I'll be able to contribute something to the codebase.
