### ISSUE TITLE
Create a postgres db dump to test /meetup/locations/

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#207]
/meetup/locations/ needs to be tested for >500 locations to check for the near to real case scenario.

**Comment by sonakshisaxena1** [comment]
![screen shot 2017-10-10 at 10 24 36 pm](https://user-images.githubusercontent.com/24795489/31417644-8efdfe98-ae4e-11e7-9b64-a29cfdc9ed26.png)

Even after adding the meetup locations along with their latitudes and longitudes, I am still unable to find any markers on the map. Is this the expected behavior? 

If so, then what are we supposed to test?
Can you please guide me a little?

**Comment by tapasweni-pathak** [comment]
@sonakshisaxena1 [This](https://github.com/systers/portal/blob/develop/systers_portal/templates/meetup/snippets/meetup_locations_map.html#L15) should be doing it. For this issue a dump is required.

**Comment by sa7i** [comment]
@tapasweni-pathak: Hey, I have a script which can seed this. Currently I'm using random and filling events with random strings. The parameters are numbers -will this do? Here's the code - I can refine this and push it in a while. 

Do you require a dump or shall I merge this code itself in? 

![screenshot from 2017-10-14 21-55-29](https://user-images.githubusercontent.com/13400691/31577385-ed19b8c6-b12a-11e7-9918-db99832d712e.png)

**Comment by sa7i** [comment]
More relevant screenshot - I've seeded as well with 500 meetings. You can view the changes [here](https://github.com/systers/portal/compare/develop...sa7i:develop).

![screenshot from 2017-10-14 22-40-19](https://user-images.githubusercontent.com/13400691/31577685-e22176ba-b130-11e7-9239-eec520aaa3c8.png)

**Comment by tapasweni-pathak** [comment]
This looks great! Can you work on integrating it with Travis? You can assert on the response.

**Comment by tapasweni-pathak** [comment]
Closed with 14fae7db14ec8c1f54cd5c8f9325f5e8ba769712.
