### ISSUE TITLE
Link contact page on /accounts/password/reset/

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#209]
- [x] Below change password button, link **contact** with /contact/.
- [x] Also on /accounts/password/reset/done/.

**Comment by sunakshi96** [comment]
@tapasweni-pathak Is this issue still open? (Since there is a fix referenced to this issue 11 days ago)

**Comment by tapasweni-pathak** [comment]
It has two todos, one is fixed with #219.

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak 
The second to-do was fixed earlier and now I have created a pull request for the first one. Please check it once.
