### ISSUE TITLE
Override /users/username/profile/ choose file button to the general style guide of the website

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#210]
For registration/authentication we use django-allauth. This package has basic templates for the required pages. Almost all of them have already been overriden. Override the choose file button to the general style guide of the website. If you find something else feel free to update that too.

**Comment by sonakshisaxena1** [comment]
![screen shot 2017-10-11 at 6 39 39 am](https://user-images.githubusercontent.com/24795489/31417703-ec63a65a-ae4e-11e7-8824-39cb83af1224.png)

I am unable to find any **Browse** button. :(
Are we supposed to change the **Choose File** button as per the general style instead?

**Comment by sunakshi96** [comment]
@tapasweni-pathak Can you please be more explicit in the explanation ?  :)

**Comment by tapasweni-pathak** [comment]
Woops! updated it. Thanks both of you for pointing it out.

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak I just figured it out that this issue has already been solved by **crispy-forms** and soon will be coming with the next [release](https://l.messenger.com/l.php?u=https%3A%2F%2Fgithub.com%2Fdjango-crispy-forms%2Fdjango-crispy-forms%2Fissues%2F734&h=ATOGiDw2x4ZWgpcWqy9qw4A7RdZGmUuQOB7szXCcoLNUq0KqVLp6cDQeY8OREnp2iLOqGWuPrdzSeypPHCbwnzjB5B3CZbXTVWpj5i9_AumBmrhgBfCpVH62HkMBscjD8phwLaPQbB7ove_Qqk0) of the same and hence doesn't need fixing any more.

**Comment by tapasweni-pathak** [comment]
Thanks for figuring it out, I will keep this open until we adapt to the new one.

**Comment by sa7i** [comment]
[Update] Crispy forms got upgraded and the browse button looks like this. @tapasweni-pathak does this need improvement? 
![image](https://user-images.githubusercontent.com/13400691/36886437-659f20ac-1e12-11e8-9f3d-b914dd887a05.png)

**Comment by tapasweni-pathak** [comment]
Yea @sa7i, needed. 👍
