### ISSUE TITLE
Country dropdown values

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#211]
Check for country dropdown values in /users/username/profile/, no values appear.

**Comment by ankita240796** [comment]
![selection_001](https://user-images.githubusercontent.com/15226041/31052216-ff22721e-a69a-11e7-8ed6-81a9e8d2a1a1.png)
@tapasweni-pathak country dropdown values are there. Can you have a look ! 
Thanks

**Comment by tapasweni-pathak** [comment]
Can you please also setup the portal develop branch in your local and check if you are getting the list of countries there?

**Comment by ankita240796** [comment]
Okay ! I checked in my local, list of countries is not there. I am looking into this matter.
Thanks
