### ISSUE TITLE
Generated URL in password reset has an extra protocol name

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#212]
What I get is

![screenshot from 2017-09-30 08-29-28](https://user-images.githubusercontent.com/4143778/31041851-bc135f10-a5b9-11e7-938b-147ec88e6d19.png)

**Comment by sa7i** [comment]
This looks fine in the dev version, emitted mail is below. Looks to be handled by the django account module internally, I couldn't find something in the portal code which lets me tweak this.  How exactly do I reproduce the bug? 

```
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [example.com] Password Reset E-mail
From: webmaster@localhost
To: <e-mail>@gmail.com
Date: Sun, 01 Oct 2017 17:02:04 -0000
Message-ID: <20171001170204.3994.44645@evil.localdomain>

You're receiving this e-mail because you or someone else has requested a password for your user account at example.com.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

http://127.0.0.1:8000/accounts/password/reset/key/2-4px-472453cd282c199f36c3/

In case you forgot, your username is poojitha.

Thanks for using our site!
```

**Comment by tapasweni-pathak** [comment]
Can you please also check on the website, I find this issue there. It works in local. 😕

**Comment by sa7i** [comment]
I checked the site and can see the same error. 

The way I understand, this is handled internally by the [auth](https://github.com/django/django/blob/89559bcfb096ccc625e0e9ab41e2136fcb32a514/django/contrib/auth/forms.py#L235). I further tracked it to a [get_current_site()](https://github.com/django/django/blob/master/django/contrib/sites/shortcuts.py). Maybe the way it is deployed might have something to do with it? Can you help me out?

**Comment by sonakshisaxena1** [comment]
Hey, @tapasweni-pathak, I checked this on the website and did get an email with the extra protocol name but no email is received when I go for reset password in local. How should I check if the fixes I am trying to make and working properly or no?

**Comment by sonakshisaxena1** [comment]
Hey, I checked both the dev and the site version of this. Since only the site shows this extra protocol, I feel that making any changes to it won't resolve the issue since we are not sending any email through the local version.
Can you please guide me if I am wrong?

**Comment by sa7i** [comment]
@tapasweni-pathak While resetting portal-dev's password, I noticed that it doesn't have an extra protocol name. I think this bug no longer exists.
![image](https://user-images.githubusercontent.com/13400691/32160694-d74ad822-bd78-11e7-8a9e-4dde3e808dfd.png)

**Comment by arunikayadav42** [comment]
Is this bug still an issue?

**Comment by arunikayadav42** [comment]
I want to work on this issue,can somebody please guide me regarding the work that has to be done?

**Comment by sa7i** [comment]
This bug doesn't exist now
