### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady error received while migrating

### ISSUE THREAD

**Issue by sonakshisaxena1** [systers/portal#220]
On using the following command:

`python3 manage.py migrate`

I get the following traceback:

`File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)`

  `File "<frozen importlib._bootstrap>", line 978, in _gcd_import`
 ` File "<frozen importlib._bootstrap>", line 961, in _find_and_load`
  `File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked`
 ` File "<frozen importlib._bootstrap>", line 655, in _load_unlocked`
  `File "<frozen importlib._bootstrap_external>", line 678, in exec_module`
  `File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/community/__init__.py", line 1, in <module>
    import community.signals  # NOQA`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/community/signals.py", line 1, in <module>
    from django.contrib.auth.models import Group`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()`

  `File "/Users/sona/Downloads/portal-develop/systers_portal/venv/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready`

    `raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

I tried to resolve it and I think that  `import community.signals` in `systers_portal/community/__init__.py` is not getting imported to `settings.py`, but I don't know how to remove it. Please guide me in this.

![screen shot 2017-10-05 at 8 51 49 pm](https://user-images.githubusercontent.com/24795489/31235395-12ae93d6-aa0f-11e7-8d9b-b2ca31265f91.png)

**Comment by tapasweni-pathak** [comment]
@sonakshisaxena1 If this got fixed for you please update this issue with your environment details and the fix.
