### ISSUE TITLE
Redirect screenflow after sending/cancelling Community Join Request

### ISSUE THREAD

**Issue by verma-varsha** [systers/portal#222]
When the user clicks on the "JOIN COMMUNITY" button, he is being redirected to the user home as shown in the next screenshot.

![screenshot from 2017-10-06 12-08-10](https://user-images.githubusercontent.com/20443665/31266265-959501aa-aa90-11e7-9235-9f7fa9660f5f.png)
![screenshot from 2017-10-06 12-10-18](https://user-images.githubusercontent.com/20443665/31266399-442ca2d6-aa91-11e7-88c2-ab46170b21ef.png)

This is quite absurd and unusual as far as the user experience is concerned. A better design workflow to the above scenario would be to redirect the user to the same page with just the "JOIN COMMUNTIY" button changed to "CANCEL REQUEST" button as shown in the image below (Of course, with the user being on the same community subpage that he was on earlier).
![screenshot from 2017-10-06 12-08-27](https://user-images.githubusercontent.com/20443665/31266340-ebe1fe3c-aa90-11e7-962f-96a016d2ff0e.png)

**Comment by verma-varsha** [comment]
@tapasweni-pathak Could you please assign this task to me as I am already working on it. Thanks!

**Comment by tapasweni-pathak** [comment]
Issues can be only assigned to people within the org/project. Looking forward to the fix, for this, by you.  Thanks for the issue. :)
