### ISSUE TITLE
Create custom 404, 403, 500 error pages

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#223]
[Django documentation](https://docs.djangoproject.com/en/1.11/topics/http/views/#customizing-error-views)

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak I am working on this.
I need to make these pages in template folder right?

**Comment by tapasweni-pathak** [comment]
> I need to make these pages in template folder right?
Yes, also in views.
> Also I am not able to add myself to slack page , please add me himanshikhandelwal8@gmail.com
I am facing some issues in running it with the given django version

Can you please drop an email to May regarding this? You can read [this](https://github.com/systers/ossprojects/wiki/Outreachy-Round-15-(September-2017)#communication) for more.

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak  I have mailed twice , but still not added. I am facing problem in setting this up.

**Comment by tapasweni-pathak** [comment]
Done over the email. :) Feel free to raise issue and then close with how you fixed the issue with installation. Closed issues tagged as *While Setting up Portal" may help.
