### ISSUE TITLE
Add and change user email address

### ISSUE THREAD

**Issue by ninjakx** [systers/portal#230]
No option for correcting the user email address in the portal.

**Comment by tapasweni-pathak** [comment]
@ninjakx Can you please explain a bit more? Please update this pull request with what is the current behavior and what you think would make Portal better.

**Comment by ninjakx** [comment]
There can be 2 cases :
1) User has made a typing mistake in filling email id in signup form .Then he/she won't receive any email confirmation.
2) User has lost the access to his/her email account . Then he/she will not receive any mail from the organisation.  

There should be Add /Remove email account option in the edit profile.

**Comment by tapasweni-pathak** [comment]
Edit profile will only appear once the user successfully signs in. If they mistyped the email and if that email exist the confirmation will go on that, if not user has to again fill the signup form.

Please raise a new issue writing about 2 with enabling change primary email or add a new new email in edit profile section. Closing this one just to keep things clean.
