### ISSUE TITLE
Password validation 

### ISSUE THREAD

**Issue by ninjakx** [systers/portal#234]
Strengthening the password in signup form
There should be atleast
• 1 digit
• 1 uppercase letter
• 1 special character

It should display  what is missing in the password when criteria is not met
and also minimum length of username should be 5 .

**Comment by ninjakx** [comment]
I would like to create PR for this issue.

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak this issue is solved. Any changes to be done?

**Comment by tapasweni-pathak** [comment]
Closed with a398c6d0edd910a186b4d9df4f3c27d5009ec504. Thanks @Himanshi-Khandelwal for pinging me on this.
