### ISSUE TITLE
Lack of static root creates issues while trying to use debug=False case.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#246]
I have encountered this issue while trying to solve #233. 
To reproduce the bug, set `debug = False,` add  `ALLOWED_HOSTS= ['*']` in settings/dev.py file and run the server.

Only when `debug = True` , static is enabled, because of this.
https://github.com/systers/portal/blob/97f44df8379cb0332fae1cc31be17b62752ef5d9/systers_portal/systers_portal/urls.py#L38

I'd like to solve this issue.

**Comment by tapasweni-pathak** [comment]
I was about to raise this one. Please go ahead.

**Comment by sa7i** [comment]
@tapasweni-pathak: I did some more reading - I found that deploying static files requires a different technique, and hence the urls.py if condition exists. [(more info)](https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-static-files-during-development)

**Comment by sa7i** [comment]
According to [this,](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#cmdoption-runserver-insecure)

> python manage.py runserver --insecure 

would test the error pages during local deployment without having to remove the urls.py if condition.
