### ISSUE TITLE
Full password requirements are never provided to user

### ISSUE THREAD

**Issue by nathalier** [systers/portal#247]
clean_password() function is a little bit misleading in its tries to help user to create good password.

Let's consider the case when user creates password 'pass123'. 
He gets message: "Password must have at least one uppercase letter and one special character."
He tries 'passA!A' and gets new error message "Password must have at least one digit".
This is quite embarrassing - he previously entered password with digits but was rejected to use it.

If a password does not meet requirements - all rules should be provided to user: "Password must have at least 6 characters. Password must have at least one uppercase letter, one special character and one digit", which improves user experience since he will not be bothered by multiple consequent error messages while discovering the rules.

**Comment by tapasweni-pathak** [comment]
Thanks for this! This will also simplify the logic.

**Comment by tapasweni-pathak** [comment]
Closed with ce6417f31397f58722a8ca3ecbaa29cfefc7bcd8.
