### ISSUE TITLE
Restrict the number of characters to be entered in the Edit Profile Fields

### ISSUE THREAD

**Issue by sonakshisaxena1** [systers/portal#250]
In the `Edit Profile` (/users/username/profile/) , the user should be allowed to enter only a minimum number of characters in the `First Name` and the `Last Name` fields.

![screen shot 2017-10-19 at 5 44 23 pm](https://user-images.githubusercontent.com/24795489/31770464-a42a106a-b4f5-11e7-9918-5800c636a283.png)

**Comment by AkshGautam** [comment]
Is these repository only dedicated to female developers? If not,can i contribute ?after getting acquainted the code

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak I have made a PR regarding this. Please review it once.

**Comment by AkshGautam** [comment]
@tapasweni-pathak thanks,i would be happy to contribute,Is there a slack channel for the organization?

**Comment by sonakshisaxena1** [comment]
@MeepMay I have already made a PR regarding this. Can you please consider it before closing the issue?
