### ISSUE TITLE
Upcoming meetups on meetup/locations page

### ISSUE THREAD

**Issue by sa7i** [systers/portal#264]
This is an enhancement task. It would be better to have upcoming meetups on meetup/location page in addition to upcoming meetups on meetup location page.
![image](https://user-images.githubusercontent.com/13400691/33336821-2b297f0e-d497-11e7-84fd-bc856dd1dc26.png)

![media-20171128](https://user-images.githubusercontent.com/13400691/33336429-e06fb2a4-d495-11e7-88aa-bfd6ffa50ed7.png)

**Comment by tapasweni-pathak** [comment]
Closed w/ 45dc32a33628af2a2ee0cb459e000ea827e8b041.
