### ISSUE TITLE
Create a new form to add a community.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#288]
Currently, users fill a google doc to request a new community, and admin can only add a new community via backend. Even when an admin can add a community via frontend, it'd still be an extra work as the number of communities increase.
Hence, approve/reject requests of new community would be better.
Admin would go through the details of the form filled by users requesting a new community and approves/rejects it, edit its details (like order) and publishes it.

**Comment by tapasweni-pathak** [comment]
You can close https://github.com/systers/portal/issues/267 and add more description about the use case in this one.

**Comment by sa7i** [comment]
@tapasweni-pathak  I will consider this as a high priority task and work on this from today.
