### ISSUE TITLE
 Create the same style for meetup tabs as community tabs.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#289]
Currently, 
Both community and meetups use nav-pills but the tabs aren't similar.
Create the same style for meetup tabs as community tabs.
![image](https://user-images.githubusercontent.com/13400691/34050023-69d87cfa-e1df-11e7-992e-ac1095ef8f8f.png)

![image](https://user-images.githubusercontent.com/13400691/34050003-5967362c-e1df-11e7-9497-4b4034047408.png)

This may be a low priority task; just putting it here.

**Comment by apoorvaagupta** [comment]
Hello, Is this issue available. 
May I take it up, if no one else is doing?
