### ISSUE TITLE
Upgrade psycopg2 to the latest version for travis to work.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#290]
As seen in one of my [PR](https://travis-ci.org/systers/portal/builds/317064729?utm_source=github_status&utm_medium=notification), travis is breaking while installing psycopg2.6.
psycopg must be upgraded to the latest version to resolve this issue.

Related issues:
https://github.com/psycopg/psycopg2/issues/594
https://github.com/travis-ci/travis-ci/issues/8897

**Comment by tapasweni-pathak** [comment]
I included this in https://github.com/systers/portal/issues/201 <=  includes migrating all the used packages to latest and compatible versions, closing this one.
