### ISSUE TITLE
Add Report, Delete Permissions for comments

### ISSUE THREAD

**Issue by sa7i** [systers/portal#294]
## Description
Currently, user can only edit or delete their own comments. But, user must also be able to report a comment and admin/organiser must be given permissions to delete the comment.

**Comment by kriti21** [comment]
@sa7i Please tell me what comments are you referring to here? I am unable to find comment section in portal.

**Comment by sa7i** [comment]
Hi @kriti21, thank you for showing interest in this.
The issues that I created are assigned to me to finish it as part of my outreachy work.
Anyway, to get to see the comment section, you have to add a meetup location from the admin panel. Once you do it, you'll also have to create a new meetup, after which you can see a discussion area where comments can be added.

**Comment by kriti21** [comment]
Thanks for the info @sa7i

**Comment by prachi1210** [comment]
Please update with issue template.
