### ISSUE TITLE
WIKI link in navbar should display a proper message instead of 404 Not found

### ISSUE THREAD

**Issue by kriti21** [systers/portal#295]
WIKI link in the navbar shows 404 Not found error message which is not very user-friendly. 
It could instead display some meaningful message (as for the link CONTACT)

## Mocks
screenshot of the error
![issue1systers](https://user-images.githubusercontent.com/19872082/34905120-8a03fa9a-f878-11e7-9f02-22838e971f36.png)

**Comment by tapasweni-pathak** [comment]
This is not reproducible on dev, closing it, thanks for the heads up just as an information the dev would lead to being live on this link.
