### ISSUE TITLE
Add option to allow signup with github

### ISSUE THREAD

**Issue by kriti21** [systers/portal#296]
The option for signing in with github is already available while signing up with github is not present. 
Add option to allow user to sign up on systers portal using his/her github account.
 
## Mocks
![portal1](https://user-images.githubusercontent.com/19872082/34915394-ee5e0552-f94b-11e7-813a-ec73fcdfc93d.png)

![portal3](https://user-images.githubusercontent.com/19872082/34915407-23feb396-f94c-11e7-90a1-8fb78533c533.png)

**Comment by kurianbenoy** [comment]
Is the project using the Ouath?
Can I add the option for setting up Signing up with github?

**Comment by prachi1210** [comment]
Please update with issue template
