### ISSUE TITLE
Add option to allow sign up with Google Account

### ISSUE THREAD

**Issue by kriti21** [systers/portal#298]
In order to make the already available Sign in option with Google account to work, it is required that a sign up option using Google account is also available.

## Mocks
![portal4](https://user-images.githubusercontent.com/19872082/34939854-5cb9aa48-fa13-11e7-94fc-a94fa26fad65.png)
![portal5](https://user-images.githubusercontent.com/19872082/34939863-6690338e-fa13-11e7-905e-cb1c8aa8d0d9.png)

**Comment by jagmeetsinghalagh** [comment]
Claim

**Comment by AnkitKhatri55555** [comment]
@kriti21 , is someone working on this?

**Comment by kriti21** [comment]
I don't think so @AnkitKhatri55555 Feel free to solve this and submit a PR :)

**Comment by imrshu** [comment]
@kriti21 I have already solve this issue could you please assign this task to me, So that i can make a PR.

**Comment by AnkitKhatri55555** [comment]
@imrshu , feel free to take another issue

**Comment by AnkitKhatri55555** [comment]
iam working on this

**Comment by prachi1210** [comment]
Please update with issue template
