### ISSUE TITLE
Implement django form for new community proposal.

### ISSUE THREAD

**Issue by kriti21** [systers/portal#301]
## Description
As of now, the form for proposing a new community is based on Google forms. Although it is fully functional but a more relevant approach would be to use django based forms as they are more reliable.

## Acceptance Criteria
All the functionality supported at present should be imported in the form and database connected.

**Comment by sa7i** [comment]
Hi, @kriti21 You're right! 
But there's already a #292 submitted to replace google form with Django forms. 
This issue can be closed.

**Comment by kriti21** [comment]
Ok @sa7i :) 
I am closing this one.
