### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by jainaman224** [systers/portal#305]
To reproduce go to http://systers.org/systers-dev/ or click Wiki from navbar of http://portal.systers.org.
Whereas link is correct in this codebase https://github.com/systers/portal/blob/235cd8ff7a6073402aee648ae18e4d11f8709ece/systers_portal/templates/base.html#L56.

**Comment by sandeepsajan0** [comment]
I am working on this issue.

**Comment by sandeepsajan0** [comment]
It occurs due to the branching of the repo. As I think this http://portal.systers.org/  site is deployed on the basis of master branch but we all are using develop branch. If you will see the code of master branch then you could understand that.

**Comment by sa7i** [comment]
Hi, currently we are using develop branch. You needn't worry about the master. Once the develop branch's portal is ready, it will be deployed into production. The issue states that the link in develop branch is working. So I don't think there can be any changes made to the code. This can be closed. Also, there are currently three links where portal is hosted.
http://portal-beta.systers.org
http://portal-dev.systers.org - Develop branch's portal soon be changed into portal-beta or portal.systers.org
http://portal.systers.org/ - the one that's in use

**Comment by sandeepsajan0** [comment]
Yeah, I got it thanks @sa7i  it helps.
