### ISSUE TITLE
User re-login after logging out and clicking back button.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#331]
## Description
As a user, when I log out and click the back button, I am able to re-login without entering any details, which is a flaw.

## Acceptance Criteria
Once logged out, the user mustn't re-login with a back button.

### Update [Required]
- [ ] Meet the acceptance criteria

### Enhancement to Update [Optional]
- [ ] Go through Portal, and check if there are any more such flaws. If they exist, create an issue.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by imrshu** [comment]
claim

**Comment by imrshu** [comment]
@sa7i i have test this issue on several browsers (Chrome, FireFox, Ubuntu Browser) and found that it is just the browser caching problem. However i found that the problem occurs only with Firefox.
