### ISSUE TITLE
Cancel Request option must be available to users who requested to join meetup location. 

### ISSUE THREAD

**Issue by sa7i** [systers/portal#333]
## Description
As a user, when I click the "join meetup location" button I am shown a message that my request is sent.  But, there must also exist an option to cancel the request. 

## Mocks
This is already implemented in Communities. Implement it for Meetup locations.
![image](https://user-images.githubusercontent.com/13400691/36833874-e28bf3cc-1d56-11e8-83f4-db9305eb13d6.png)

## Acceptance Criteria
Necessary changes in views.py, templates and write tests for the views. You can use this https://github.com/systers/portal/blob/2db1ffc1854b5627423e1b76f35e0424249d078c/systers_portal/membership/views.py#L169 as a reference to work on this. 
The button and the flow must be similar to that of communities.

### Update [Required]
- [ ] Add a Cancel Request Button.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3/4/5 hours

**Comment by ajatprabha** [comment]
@sa7i, I would like to implement this. I'll send a PR when ready.
