### ISSUE TITLE
View improvements in users app

### ISSUE THREAD

**Issue by ajatprabha** [systers/portal#337]
## Description
The `users` app module is concerned with managing and presenting the data of a user within the `systers_portal` project. There are currently two views under `views.py` UserView and UserProfileView. While both of them have rather confusing names in accordance with what they do, one of them inherits from the wrong type of Generic Class Based View and the other uses a wrong Model class associated with it, along with other issues (explanation below). Resolving this issue will improve code quality.

If you look at [UserView](https://github.com/systers/portal/blob/develop/systers_portal/users/views.py#L12), it is inheriting from a TemplateView, but a more logical and design correct choice would be a DetailView, it will also eliminate the need of over-riding `get_context_data()`  
Issues:
- Wrong generic view used
Should be ```class UserView(LoginRequiredMixin, DetailView)``` instead of ```class UserView(LoginRequiredMixin, TemplateView)```
- Unnecessary context data update
Updating the view with ```model = SystersUser``` will remove the need to override [`get_context_data()`](https://github.com/systers/portal/blob/develop/systers_portal/users/views.py#L16)

Also if you look at [UserProfileView](https://github.com/systers/portal/blob/develop/systers_portal/users/views.py#L40), the generic view is correct but the model passed is `User` but most of the editable fields are attributes of `SystersUser`, so it'll be a better choice to pass the latter as the model.  
Issues:
- Wrong model used
The model used should be `SystersUser` instead of `User` because only [2 `User` fields](https://github.com/systers/portal/blob/develop/systers_portal/users/forms.py#L12) are being updated and [4 `SystersUser` fields](https://github.com/systers/portal/blob/develop/systers_portal/users/forms.py#L38), and in future only `SystersUser` fields are likely to update as requirements change because `User` is a Django default model.
- Object retrieval in wrong function i.e `dispatch()` instead of `get_object()`
Currently [`dispatch()` injects `self.user` and `self.systersuser`](https://github.com/systers/portal/blob/develop/systers_portal/users/views.py#L50) but `dispatch` is meant to handle `http request types` and `get_object()` should be used to return a `SystersUser` instance.
- Unnecessary context data update
Again, if `SystersUser` model is used, overriding [this](https://github.com/systers/portal/blob/develop/systers_portal/users/views.py#L62) will not be needed.

### Update [Required]
- [ ] Refactor users app with above points in mind and without changing functionality
- [ ] Update tests, write new ones if necessary
- [ ] Update necessary form classes in forms.py
- [ ] Update templates

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Time Estimation
Should be done in stages with continuous feedback from mentors.

cc: @MeepyMay @tapasweni-pathak 
PS: I'd like to discuss further on this issue and create a PR to resolve the same.

**Comment by sa7i** [comment]
@ajatprabha Before you start working on this, please get an approval from @tapasweni-pathak

**Comment by ajatprabha** [comment]
Closing this issue in favour of #354.
