### ISSUE TITLE
Permissions for user not being shown on home screen

### ISSUE THREAD

**Issue by sammy1997** [systers/portal#339]
## Description 
As a user,
I need to grant permissions to the user(let's say from admin),
and then view your profile. No permissions will be shown.

## Mocks
![portal](https://user-images.githubusercontent.com/24635701/36896464-d085d836-1e38-11e8-8548-9203d35defb3.png)
![portal_error](https://user-images.githubusercontent.com/24635701/36896466-d1047f6a-1e38-11e8-9006-956cd85030f6.png)

## Acceptance Criteria
- [ ] The permissions available for the user should show in the home screen.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour 

#Tag - beginner

Please review this @sa7i @tapasweni-pathak @prachi1210.

**Comment by sammy1997** [comment]
Please review this. I would like to work on this.

**Comment by sa7i** [comment]
@sammy1997 Yes, they aren't showing up. I opened an issue few days back and worked on it 
https ://github.com/systers/portal/issues/322

**Comment by prachi1210** [comment]
If this issue is a duplicate, it should be closed. Has this been fixed @sa7i?

**Comment by sa7i** [comment]
@prachi1210  This issue is a duplicate of #322  I fixed it, but not merged yet.

**Comment by sammy1997** [comment]
Closing this issue w.r.t #322 . Thanks .
