### ISSUE TITLE
New lines not being visible in the comments.

### ISSUE THREAD

**Issue by abhi20161997** [systers/portal#348]
## Description
As a [USER],
I need [to comment in the discussion area and hit enter to start off the next piece of text in the second line],
so that I can [].

## Mocks
![screenshot from 2018-03-08 20-54-39](https://user-images.githubusercontent.com/23247839/37172928-43e44c1e-2338-11e8-8506-02c08c79995c.png)

### Update [Required]
- [ ] [When I press enter while feeding comments the new line texts should be visible on separate lines.]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[15] minutes

**Comment by abhi20161997** [comment]
@Janiceilene @sa7i @tapasweni-pathak  Please review this so that I could fix it at the earliest.

**Comment by yatna** [comment]
@abhi20161997 I am not able to replicate your bug. Can you tell which comment area are you talking about.

**Comment by sa7i** [comment]
@yatna There are discussion areas(Comments) in the meetups and support requests. You can see it after adding a meetup location and a meetup in the meetup location.
