### ISSUE TITLE
Bootstrap library should be updated for new features and glyphicons to be available

### ISSUE THREAD

**Issue by sammy1997** [systers/portal#351]
## Description
As a devloper,
I saw that the Bootstrap library being used is an older version, which is why some of the new features and icons (glyphicons) are not available.

## Mocks
-- N.A. --

### Update [Required]
- [ ] Update the bootstrap library

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 mins

**Comment by sammy1997** [comment]
@prachi1210 @ramitsawhney27 @tapasweni-pathak @sa7i Can you have a look at this issue ? If it's valid , I can work on this.

**Comment by yatna** [comment]
@sammy1997 I think we should be using Bootstrap CDN instead of static downloaded bootstrap to keep updated. If done so- 
1. It would remove the need of updating bootstrap every time there is a new release.
2. It would decrease the code size of the project.

**Comment by sammy1997** [comment]
Agreed @yatna. Do you want me to send a PR making this change?

**Comment by sammy1997** [comment]
@yatna @sa7i Do I go ahead with this?

**Comment by m-murad** [comment]
@sammy1997 
This is a valid issue,
I think this should be fixed. Please send a PR.

**Comment by sammy1997** [comment]
Thanks @m-murad . I will send a PR soon.
