### ISSUE TITLE
NoReverseMatch exception for news_slug with hyphen

### ISSUE THREAD

**Issue by ajatprabha** [systers/portal#355]
## Description
As a developer,
I need fix the regex that matches against `news_slug` in `blog.urls`,
so that I can resolve `NoReverseMatch` exception.

## Mocks
The existing regex doesn't account for hyphens in a slug which results in regex mismatch and in turn, raises the above-mentioned exception.
![selection_003](https://user-images.githubusercontent.com/11836668/37368071-2273d864-272b-11e8-9ea3-0c84ba4f9fce.png)
https://github.com/systers/portal/blob/3d870165ad0b93e55c084a2e463bede642ec6ff3/systers_portal/blog/urls.py#L16-L21

### Update [Required]
- [ ] Fix the regex to accept hyphens

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10-20 minutes

**Comment by yatna** [comment]
Is an underscore ( _ ) working? If yes, why not use that instead of hyphen. I think it would be best if a convention is defined as in what is allowed and what is not.

**Comment by ajatprabha** [comment]
@yatna, `\w` accepts underscore as well, in general, it accepts `[A-Za-z0-9_]`. A `[\w-]` should be sufficient here. Please have a look at core validator used by Django itself.
https://github.com/django/django/blob/master/django/core/validators.py#L235-L241
Thanks for the input.

**Comment by sa7i** [comment]
You can work on this. @ajatprabha
