### ISSUE TITLE
Change Pixelated PNG coverage Badge

### ISSUE THREAD

**Issue by aashutoshrathi** [systers/portal#356]
## Description
As a contributor/visitor, first glance at coverage badge defines our project, here the coverage Badge is somehow added in PNG format, which is pixelated one, we need to change it to SVG, which is recommended for MD files.

## Mocks
New Badge will be this:

[![Coverage Status](https://coveralls.io/repos/github/systers/portal/badge.svg?branch=master)](https://coveralls.io/github/systers/portal?branch=master)

While current one is this: 

[![Coverage Status](https://coveralls.io/repos/systers/portal/badge.png?branch=master)](https://coveralls.io/r/systers/portal?branch=master)

### Update [Required]
- [x] Changing badge url and refrence.

## Definition of Done
- [ ] Approval by 1 mentor.
- [x] All of the required items are completed.

## Estimation
1 hours

**Comment by sa7i** [comment]
@aashutoshrathi You can work on this.

**Comment by aashutoshrathi** [comment]
Thanks :+1: on it.
