### ISSUE TITLE
ReadTimeoutError : pip install -r requirements/dev.txt

### ISSUE THREAD

**Issue by Fenn-CS** [systers/portal#360]
## Description
During the configuration of systers portal developers may run into the 

> ReadTimeoutError with pip

That's at precisely step six : pip install -r requirements/dev.txt

## Solution

Increase the default timeout for HTTP socket connections. 

`sudo pip3 install --default-timeout=100 -r requirements/dev.txt`

_Additionally I think its better to use pip3 during set up, since it is updated and python3 is being used._

**Comment by Fenn-CS** [comment]
Hopefully the "While Setting up Portal" label is added to this issue.

**Comment by pavankm** [comment]
Is this a consistently reproducible issue and not dependent on the network or possibly some downtime at pypi?

**Comment by Fenn-CS** [comment]
AFAIK, I think its dependent on the network! It can be reproduced steadily on a network with poor IP configurations or a slow Internet connection. However given the large number of possibilities I believe we should have this  in case anyone gets into it.

**Comment by yatna** [comment]
@Fenn-CS This is not a project specific error , hence, I think It should not be included in the main installation part. However, it could be given at the end as a footnote or a "Troubleshooting' section.

**Comment by Fenn-CS** [comment]
@yatna makes sense! So I will just add a troubleshooting section to the docs reference and reference it here! So we can close the issue, if its not already eligible for closing.

**Comment by sa7i** [comment]
I am closing this issue as discussed.
