### ISSUE TITLE
No enviroment instructions for windows developers

### ISSUE THREAD

**Issue by Fenn-CS** [systers/portal#362]
## Description
Even though unix systems are best, we have several  developers working on windows. Apart from Docker there are no instructions to help new windows developers get to speed with the project directly on their working environment.

## Mocks
![setup instructions](https://user-images.githubusercontent.com/14317775/38739169-08b10c62-3f2c-11e8-8b64-4f781dce7bd0.png)

### Update [Required]
- [ ] Add windows specific instructions for portal setup

## Definition of Done
- [ ] Instructions added and tested (by configuring in windows environment)
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by MeepyMay** [comment]
Please update to the template. Thank you!

**Comment by Fenn-CS** [comment]
@MeepyMay update done, please review. Thanks for your time.
