### ISSUE TITLE
Position the "Request a New Meetup Location" into the meetups dropdown.

### ISSUE THREAD

**Issue by sa7i** [systers/portal#366]
## Description
As a user, I need to see a "Request a New Meetup Location" on the meetups dropdown and not on the meetup location sidebar, so that it's similar to that of "Request communities" and independent of any meetup location page.

### Update [Required]
- [ ] Position the "Request a New Meetup Location" into the meetups dropdown.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
< 1 hour

**Comment by Fenn-CS** [comment]
@sa7i Can I work on this?

**Comment by sa7i** [comment]
@Fenn-CS You can work on this.
