### ISSUE TITLE
API to communicate with VMS

### ISSUE THREAD

**Issue by abhi20161997** [systers/portal#411]
## Description
Create an API to send data of meetups like event name, date and venue to VMS.

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[8-9] hours

**Comment by sa7i** [comment]
Requirements of the API - [link](https://docs.google.com/document/d/1QPkIEXXg8iS4m7miAbt6Qt17CeSnqyYCrDDq0g__ngY/edit?usp=sharing)
