### ISSUE TITLE
Remove testing error in test_views.py

### ISSUE THREAD

**Issue by Tlazypanda** [systers/portal#450]
## Description
The following  command throws assertion error when run in the meetup/test_views.py file.
`python systers_portal/manage.py test --settings=systers_portal.settings.testing`.

## MOCKS
![screenshot from 2018-11-08 05-44-57](https://user-images.githubusercontent.com/33183263/48153087-6e44e180-e2eb-11e8-8a50-f883778fddc5.png)

### Update [Required]
- [ ] Remove assertion error.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by abhi20161997** [comment]
@Tlazypanda  Please include mocks of the error you are getting in the issue description. Also, browse through other issues to get an idea of how issues are created omitting words like I and as a developer.
