### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#47]
When uploading a high resolution photo/image (the one I used was 2186 x 2112), the application crashed with error displayed. See image below. Currently used a 180 x 135 size photo.

![error](https://cloud.githubusercontent.com/assets/63290/3791654/a2e4b4d2-1b4a-11e4-9b19-c9621f885510.png)

**Comment by ana-balica** [comment]
Tested with a 5184 × 3456px picture.
Due to the inability to replicate the problem, closing the issue.
