### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#48]
When everyone visits the portal, whether they are logged in or not, no matter if they are admins for other communities (latinas, bwic, etc.), they should land at the Systers home page. 

For example
If I am a Syster, AsianWiC and IndianWiC, I should have at the top navigation bar,

Systers | About | Sub-Communities | 
                         | UWiC |  
                                     | BWiC |
                                     | LiC |
                         | LGBT| 
                         | TurkishWiC| 
                         | ArabWiC | 
                         | AsianWiC | 
                                           | ChineseWiC | 
                                           | FilipinasInC | 
                                           | IndianWiC |

**Comment by iCHAIT** [comment]
@rosariorobinson Can you shed some more light on this?
