### ISSUE TITLE
No error message for incorrect password

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#52]
When I do NOT enter correct password when I login, error message should be displayed properly.

![image](https://cloud.githubusercontent.com/assets/63290/4356203/baa741f6-4256-11e4-8e11-574ab744e7d0.png)

**Comment by tapasweni-pathak** [comment]
@rosariorobinson Can this now be reproduced? I'm not able to reproduce on portal-dev or on local installation.

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak currently it is showing error message for incorrect password. So what else needs to be done in this?

**Comment by tapasweni-pathak** [comment]
Thanks for checking and confirming.
