### ISSUE TITLE
Correct the Github Link on the Contact Page

### ISSUE THREAD

**Issue by sakshi1499** [systers/portal#574]
## Description
As a user,
I should be able to see the correct GitHub Page.

## Mocks
![image](https://user-images.githubusercontent.com/42520146/86624412-e5f77200-bfe0-11ea-9308-fc086d0fe187.png)

### Update [Required]
- [ ] Correct the link associated with the GitHub icon.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by vj-codes** [comment]
Heyy I would like to work on this

**Comment by sakshi1499** [comment]
@vj-codes Vaishnavi is this your first time making a PR in portal? Its strictly a first timer issue. ☺️

**Comment by vj-codes** [comment]
yupp @sakshi1499
