### ISSUE TITLE
add python-decouple for handling the environment variables

### ISSUE THREAD

**Issue by theyashshahs** [systers/portal#580]
## Description
As a member,
I need to add python-decouple to manage the **DJANGO SECRET KEY** and other sensitive env variables,
so that I can easily set up the project.

### Update [Required]
- [ ] settings/base.py
- [ ] settings/dev.py
- [ ] requirements/prod.txt
 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by saideepesh000** [comment]
@sakshi1499  Can I try this.

**Comment by theyashshahs** [comment]
@saideepesh000 go for it 👍

**Comment by saideepesh000** [comment]
@yashshah2820 @sakshi1499, For now, what should I keep in the .env file

**Comment by theyashshahs** [comment]
@saideepesh000 you can use the env variables used in the [README](https://github.com/anitab-org/portal/blob/develop/README.md) like `SECRET_KEY='foobarbaz'` and the env variables in base.py and dev.py 😃

**Comment by saideepesh000** [comment]
@yashshah2820  Ok, what should I keep the database password in env. And a small doubt, why are we not updating production.py with python-decouple, because that's going to be on the hosted part.

**Comment by theyashshahs** [comment]
@saideepesh000 it's all in the README
