### ISSUE TITLE
LinkedIn link broken on Contact Page

### ISSUE THREAD

**Issue by sakshi1499** [systers/portal#583]
## Description
As a user,
I need to have the correct linkedIn link,
so that I can easily reach out and contact.

Redirect the current link to this [link](https://www.linkedin.com/company/anitab-org/) instead.

## Mocks
![image](https://user-images.githubusercontent.com/42520146/87219695-17729380-c37b-11ea-8bd8-a53fe0408153.png)

### Update [Required]
- [ ] LinkedIn icon should redirect to the correct linkedIn page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sakshi1499** [comment]
@mayburgos Do we have a Linkedin page or should we remove the Linkedin icon?

**Comment by sakshi1499** [comment]
For now I think we can link it to this page [Link](https://www.linkedin.com/company/anitab-org/)

**Comment by saideepesh000** [comment]
@sakshi1499 Can I work on this issue.

**Comment by sakshi1499** [comment]
Is this your first time contributing to Portal? Its a strictly first timer issue.@saideepesh000

**Comment by saideepesh000** [comment]
Yes. It's my first time.
