### ISSUE TITLE
Correct the Twitter link on Contact Page

### ISSUE THREAD

**Issue by sakshi1499** [systers/portal#585]
## Description
As a user,
I need to have the correct twitter link,
so that I can easily connect on Twitter.

Redirect the current link to this [link](https://twitter.com/anitab_org) instead. 

## Mocks
![image](https://user-images.githubusercontent.com/42520146/87230818-cb9e0980-c3cf-11ea-8756-4de1ee16ab90.png)

### Update [Required]
- [ ] Correct the link

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Adeola-Adesoba** [comment]
Hi @sakshi1499  can I work on this?

**Comment by ritwickraj78** [comment]
@Adeola-Adesoba Go Ahead! Best of Luck :)

**Comment by sakshi1499** [comment]
This issue has been resolved.
