### ISSUE TITLE
README.md should be updated

### ISSUE THREAD

**Issue by saideepesh000** [systers/portal#591]
## Description
As a developer,
In windows, I need to activate the virtual environment using '.\venv\Scripts\activate', but the README.md shows './venv/Scripts/activate'.
so that I can activate the virtual environment correctly.

### Update [Required]
- [ ] Update README.md file.

## Estimation
1 hour

**Comment by SanketDG** [comment]
Did you mean `.\venv\Scripts\activate.bat`?

**Comment by saideepesh000** [comment]
Yes @SanketDG, I spent a whole day to figure out the issue :)

**Comment by khushishikhu** [comment]
can i work on this issue?

**Comment by khushishikhu** [comment]
@saideepesh000  can i work on this issue?

**Comment by SanketDG** [comment]
@khushishikhu You are assigned! Let us know if you need any help
