### ISSUE TITLE
Style Sign up page

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#60]
Go to `http://127.0.0.1:8000/accounts/signup/`. Page contains a sign up form, but it has no style.

In order to apply styling to this page, it is required to override the default style of django-allauth. Before proceeding, you can take a look at the [django-allauth documentation](http://django-allauth.readthedocs.org/).

Create a new file - `systers_portal/templates/account/signup.html`. This file will override the django-allauth template, which can be found inside the package - `allauth/templates/account/signup.html`. Move all the important parts to new signup template (form variable, urls, titles).

The template should be based on bootstrap3, be responsive, preferably centered. 

Example - http://portal.systers.org/accounts/signup/

As reference see [login.html](https://github.com/systers/portal/blob/develop/systers_portal/templates/account/login.html).

**Comment by kanika2107** [comment]
I want to work on this issue.
