### ISSUE TITLE
Add a badge to join Zulip chat on README 

### ISSUE THREAD

**Issue by isabelcosta** [systers/portal#600]
## Description

As a new contributor,
I need know which chat can I join regarding this project,
so that I can discuss this project with the community.

I did something similar in here https://github.com/anitab-org/mentorship-backend/pull/683

## Mocks

![image](https://user-images.githubusercontent.com/11148726/87972817-7775e200-cabf-11ea-8073-6dc6f8a1b794.png)

### Update [Required]
- [ ] Add Zulip chat badge to README with link to Zulip stream dedicated to #vms (Link: https://anitab-org.zulipchat.com/#narrow/stream/222540-portal)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sakshi1499** [comment]
@isabelcosta Hi! Can you please crop the image a little bit, it seems like its for Mentorship System and also change #vms to #portal instead. Thank you :)

**Comment by saideepesh000** [comment]
I only have 1 commit to this repository, can I do this :)

**Comment by sakshi1499** [comment]
@saideepesh000 Its a first timer issue, if no one claims it, we'll assign you but for now we should let first timers take it.

**Comment by isabelcosta** [comment]
@sakshi1499 yess I will crop it! thank you for the suggestion

**Comment by saideepesh000** [comment]
@sakshi1499 Ok, thanks

**Comment by SHITIZ-AGGARWAL** [comment]
hello  @isabelcosta 
I am new to open source and very much like to work on this issue
if you may ,please guide me and assign this issue to me

**Comment by Aaishpra** [comment]
@isabelcosta @sakshi1499 can i work on this.

**Comment by isabelcosta** [comment]
@SHITIZ-AGGARWAL I can assign this to you.
@Aaishpra if @SHITIZ-AGGARWAL is unavailable to work on this, then I can assign this to you :)

**Comment by Aaishpra** [comment]
No problem @isabelcosta
