### ISSUE TITLE
Add Tests For Subscription Settings

### ISSUE THREAD

**Issue by ritwickraj78** [systers/portal#609]
## Description
As a [USER],
I need to add unit tests for subscription settings,
so that I can increase code coverage.

### Update [Required]
- Tests for the views and forms is to be added

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12 hours

**Comment by sakshi1499** [comment]
Has been merged in another PR. Closing this issue as it was a duplicate.
