### ISSUE TITLE
Display community page content

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#61]
Prerequisites:

1. Create a superuser from the command line, if you don't have one yet. `python systers_portal/manage.py createsuperuser`.
2. Login to the admin panel (http://127.0.0.1:8000/admin) and create a new Community. Also create one or more Community Pages for this new Community.
3. Go to http://127.0.0.1:8000/community/community_slug/

The task is to display the contents the Community Page below the pills (bootstrap blue elements).

Look into `systers_portal/community` app. The view that is necessary to update is `CommunityPageView`. For portal we are using class-based views, so take your time to get familiar with CBV in Django, if you haven't worked with them before. Most probably you will need to override method `get_context_data(self, **kwargs)` to add CommunityPage object to the context.

Create a new template - `systers_portal/templates/community/page.html`. It should extend the community base template and change the block `title` and 
`community_page_content`.

Feel free to adjust the looks using CSS. As reference for good reading text size and style, see news page - http://127.0.0.1:8000/community/systers/news/ (of course, you need to create some news for the community).

**Comment by kanika2107** [comment]
I want to work on this issue.
