### ISSUE TITLE
Add info about createsuperuser to docs

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#62]
Since Django introduced migrations, [running migrate command doesn't prompt to create a superuser](https://docs.djangoproject.com/en/1.7/ref/django-admin/#migrate-app-label-migrationname). Normally it is useful to have one superuser to access the admin panel and manipulate the data.

Add to `README.md` a line after migration on how to create a superuser.

Read more about documentation here - https://github.com/systers/portal#documentation

**Comment by kanika2107** [comment]
Hi, I would like to work on this issue as my first practice for systers/portal.
