### ISSUE TITLE
Pinboard Backend and Tests

### ISSUE THREAD

**Issue by SanketDG** [systers/portal#638]
## Description
As a user,
I need to have a bookmarking/pinboard facility,
so that I can easily navigate them.

This issue is to implement the backend part of the Pinboard

## Mocks
![image](https://user-images.githubusercontent.com/42520146/89126513-b6665780-d503-11ea-8eb8-75383857e09d.png)

## Acceptance Criteria
- Must have tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 3 days

**Comment by ritwickraj78** [comment]
PR already merged !!
