### ISSUE TITLE
Add setting up env file in README

### ISSUE THREAD

**Issue by SanketDG** [systers/portal#642]
## Description
As a newcomer to this project, I need to know how this project needs to be setup the easiest way.

#592 adds support for loading configuration variables through a `,env` file, but there is no corresponding
documentation for it.

@saideepesh000 I cannot seem to assign you but feel free to start working on this

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by saideepesh000** [comment]
@SanketDG, I'll try to PR it as soon as possible.

**Comment by saideepesh000** [comment]
@SanketDG, Should I add a separate section like "Run app" like in mentorship project or add the configuration setup for both "Linux" and "Windows".

**Comment by SanketDG** [comment]
> add the configuration setup for both "Linux" and "Windows".

This seems good to me!

**Comment by saideepesh000** [comment]
@SanketDG, is this OK. 

    ......
    Create systersdb database, where systersdb might be any suitable name.

    Open the SQL Shell for postgresql from the windows start menu or wherever accessible

    $ Server [localhost]:  Just press enter, leave this empty
    $ Database [postgres]: Just press enter, leave this empty
    $ Port [5432]: This is the default port just press enter, leave this empty
    $ Username [postgres]: This is the default username just press enter, leave this empty
    $ Password for user postgres: Input password you created during installation and press enter
    $ CREATE USER <anyname you want e.g systers> WITH PASSWORD 'your password';
    $ CREATE DATABASE systersdb;
    $ \c systersdb;
    $ GRANT ALL PRIVILEGES ON systersdb TO <username created above>;

### After the database setup

    Make sure to rename .env.example to .env.

    Update the values in the .env file with the corresponding values like below.

    Open the .env file

    SECRET_KEY = <your-secret-key>
    GOOGLE_MAPS_API_KEY = <your-google-maps-api-key>
    DEBUG = True
    ALLOWED_HOSTS = *

    # Database settings

    DB_NAME = systersdb
    DB_USER = <your-database-username>
    DB_PASSWORD = <your-database-password>
    DB_HOST = localhost
    DB_PORT = 5432

    # Email settings

    EMAIL_HOST = localhost
    EMAIL_PORT = 1025
  
### Before running the app

    Run python systers_portal/manage.py migrate.
    .....

**Comment by saideepesh000** [comment]
I will be removing those "after the db setup" and "before running the app", just to make it understand I added here.

> 
> 
> @SanketDG, is this OK.
> 
> ```
> ......
> Create systersdb database, where systersdb might be any suitable name.
> 
> Open the SQL Shell for postgresql from the windows start menu or wherever accessible
> 
> $ Server [localhost]:  Just press enter, leave this empty
> $ Database [postgres]: Just press enter, leave this empty
> $ Port [5432]: This is the default port just press enter, leave this empty
> $ Username [postgres]: This is the default username just press enter, leave this empty
> $ Password for user postgres: Input password you created during installation and press enter
> $ CREATE USER <anyname you want e.g systers> WITH PASSWORD 'your password';
> $ CREATE DATABASE systersdb;
> $ \c systersdb;
> $ GRANT ALL PRIVILEGES ON systersdb TO <username created above>;
> ```
> 
> ### After the database setup
> 
> ```
> Make sure to rename .env.example to .env.
> 
> Update the values in the .env file with the corresponding values like below.
> 
> Open the .env file
> 
> SECRET_KEY = <your-secret-key>
> GOOGLE_MAPS_API_KEY = <your-google-maps-api-key>
> DEBUG = True
> ALLOWED_HOSTS = *
> 
> # Database settings
> 
> DB_NAME = systersdb
> DB_USER = <your-database-username>
> DB_PASSWORD = <your-database-password>
> DB_HOST = localhost
> DB_PORT = 5432
> 
> # Email settings
> 
> EMAIL_HOST = localhost
> EMAIL_PORT = 1025
> ```
> 
> ### Before running the app
> 
> ```
> Run python systers_portal/manage.py migrate.
> .....
> ```

**Comment by SanketDG** [comment]
@saideepesh000 Feel free to open a PR. It's hard to understand what you have added from here,
