### ISSUE TITLE
Create the config.yml file for the Welcome Bot

### ISSUE THREAD

**Issue by Frenzyritz13** [systers/portal#649]
## Description
 As a first time contributor,
 I need a bot to help guide my first contribution,
 so that I can follow this org's contribution guidelines.
 
 ## Mocks
 ![Screen Shot 2020-08-06 at 10 26 14 AM](https://user-images.githubusercontent.com/2440938/89543720-44299780-d7cf-11ea-82a0-bd81664f0d8e.png)
 
 ## Acceptance Criteria
 ### Update [Required]
 * [ ]  newIssueWelcomeComment is complete with the correct links to this repo.
 * [ ]  newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
 * [ ]  firstPRMergeComment is complete.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
 0.5 hours

**Comment by m-code12** [comment]
Can I take up this issue?

**Comment by Aaishpra** [comment]
@Frenzyritz13 can i work on this?

**Comment by sanchibansal340** [comment]
@Frenzyritz13 @SanketDG Can you please assign me this issue?

**Comment by sakshi1499** [comment]
@m-code12 Do you want to work on this?

**Comment by m-code12** [comment]
yes @sakshi1499

**Comment by m-code12** [comment]
@sakshi1499 I have raised a PR, please could you review it?

**Comment by m-code12** [comment]
> @sakshi1499 I have raised a PR, please could you review it?

@sakshi1499

**Comment by sakshi1499** [comment]
@m-code12 Sure! Do you want it under hacktoberfest?

**Comment by m-code12** [comment]
> @m-code12 Sure! Do you want it under hacktoberfest?

@sakshi1499 
Could you please review pr #690 , it has passed all the checks.
I have already completed hacktoberfest, thanks for asking btw.

**Comment by sakshi1499** [comment]
@m-code12 Congratulations on completing Hacktoberfest! I'll review the PR and still put the Hacktoberfest label so that you get a +1 there. Sorry for the delay on my end.
