### ISSUE TITLE
Remove workdir.0 from the repository

### ISSUE THREAD

**Issue by SanketDG** [systers/portal#654]
## Description
`workdir.0` was created accidentally, and has since found its home here at Portal.
It's time to evict `workdir.0`!

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 seconds (I am kidding, but not really!)

**Comment by harsh7in** [comment]
Hey @SanketDG can I work on this issue?

**Comment by SanketDG** [comment]
@harsh-9in Sure, I have assigned you.
