### ISSUE TITLE
Style account templates

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#69]
**This is a cumulative issue with a bunch of tasks. If you want to work on it, pick one template at a time, leave a comment about the template you are working on and submit a pull request once you are done.**

For registration/authetication we are using [django-allauth](http://django-allauth.readthedocs.org/en/latest/). This packages ships with a bunch of very basic templates for various pages. We need to override those to make them match the general style of the website.

We need to style the pages at the following urls:
- [x] http://127.0.0.1:8000/accounts/logout/
- [x] http://127.0.0.1:8000/accounts/password/change/
- [x] http://127.0.0.1:8000/accounts/inactive/
- [x] http://127.0.0.1:8000/accounts/email/
- [x] http://127.0.0.1:8000/accounts/confirm-email/
- [x] http://127.0.0.1:8000/accounts/confirm-email/(?P<key>\w+)/ the last part of the URL is the valid or invalid token
- [x] http://127.0.0.1:8000/accounts/password/reset/

In order to apply styling to any of the page, it is required to override the django-allauth template.

**Example for styling** http://127.0.0.1:8000/accounts/logout/:
Create a new file - systers_portal/templates/account/logout.html. This file will override the django-allauth template, which can be found inside the package - allauth/templates/account/logout.html. Move all the important parts to new logout template (form variable, urls, titles). Adjust the styling.

The template should be based on bootstrap3 and be responsive.

As reference see [login.html](https://github.com/systers/portal/blob/develop/systers_portal/templates/account/login.html) and [signup.html](https://github.com/systers/portal/blob/develop/systers_portal/templates/account/signup.html).

**Comment by alma-castant** [comment]
I want to work on the logout template

**Comment by alma-castant** [comment]
I want to work on the password change template

**Comment by kanika2107** [comment]
I want to work on accounts/email template

**Comment by alma-castant** [comment]
I want to work on the inactive template

**Comment by alma-castant** [comment]
I want to work on the accounts/confirm-email template

**Comment by alma-castant** [comment]
I want to work on the password/reset template

**Comment by todipratik** [comment]
@ana-balica Is the remaining one task being worked upon?

**Comment by ana-balica** [comment]
@todipratik Well, @kanika2107 started working on it and made a pull request. There are still some comments that should have been updated. Ask @kanika2107 if she still wants to work on this.

**Comment by payal97** [comment]
I want to work on the accounts/email template. Is @kanika2107 still working on it?

**Comment by SJasoria** [comment]
I would like to work on this issue.

**Comment by prachiagrawal269** [comment]
I would like to work on email template.

**Comment by prachiagrawal269** [comment]
@ana-balica Please review the PR #168 that contains the styled template for email.

**Comment by PratikDhanave** [comment]
I want to work on it
