### ISSUE TITLE
"About Us" page

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#77]
Create the "About Us" page. Convey to the general style of the website. Collect information about Systers community (http://anitaborg.org/get-involved/systers/), Systers mailing lists, maybe find a high-resolution picture with Systers members. The end result should be one or 2 paragraphs that clearly explain what is Systers and what is this website.

Should contain:
* TemplateView (place in the common app)
* url
* unittest
* template

**Comment by alma-castant** [comment]
I want to work on this
