### ISSUE TITLE
"Contact" page

### ISSUE THREAD

**Issue by ana-balica** [systers/portal#78]
Create "Contact" page. Convey to the general style of the website. Search for information on Systers page (http://anitaborg.org/get-involved/systers/). Provide a contact email or any other details that a user would expect from this page (social channels for example).

Should contain:
* TemplateView (placed in common app)
* template
* url
* unittest

**Comment by alma-castant** [comment]
I want to work on this

**Comment by Akanksha18** [comment]
i would like to work on this

**Comment by alma-castant** [comment]
@Akanksha18 I am working on this issue already ;)

**Comment by Akanksha18** [comment]
i am not sure if only one person has to work on any issue ;)

**Comment by alma-castant** [comment]
@Akanksha18 I don't think we can both work on it since it's just one page ;)

**Comment by Akanksha18** [comment]
@alma-castant  I don't think any developer's code is exaclty the same even if it is a single page :) best of luck to you, saw your comments in many issues ;)
